# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Myip < Formula
  desc "Determine your Internet-facing IP address and location from multiple sources."
  homepage "https://github.com/bengarrett/myip/"
  version "0.9.2"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/bengarrett/myip/releases/download/v0.9.2/myip_macOS_Intel.tar.gz"
    sha256 "490ca264d82cc3a48156ef4153ed384dc69ae6a4727bf9b9e6e29bc6df1a4a3f"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/bengarrett/myip/releases/download/v0.9.2/myip_macOS_M-series.tar.gz"
    sha256 "7ee46e0485a1a53e64f74df5c9627662d84ecb6ae7d069d6f8c367c771339e5e"
  end

  def install
    bin.install "myip"
  end
end
