# This file was generated by GoReleaser. DO NOT EDIT.
class Retrotxt < Formula
  desc "RetroTxt is the tool that turns ANSI, ASCII, NFO text into in-browser HTML."
  homepage "https://retrotxt.com/go"
  version "0.0.23"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/bengarrett/retrotxtgo/releases/download/0.0.23/retrotxt_macos.zip"
    sha256 "faaba4a226aaf36db475036d51b2ecd27b37075b31f96190840e24c1cb09befd"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/bengarrett/retrotxtgo/releases/download/0.0.23/retrotxt_linux.tar.gz"
      sha256 "6e79ae9692bea32c2fbbe81e041f8a1a08b7d64389a786e70b7548f06de72de0"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
      else
        url "https://github.com/bengarrett/retrotxtgo/releases/download/0.0.23/retrotxt_raspberry_pi-zero.tar.gz"
        sha256 "b029e83cc8062e7d960bfd16cf4516bd5594abcd56ad582860b33657d1cd7fb3"
      end
    end
  end

  def install
    bin.install "retrotxt"
  end
end
